# Copyright (c) 2022 The Orbit Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

name: checks
on:
  pull_request:
    branches:
      - 'main'

permissions: read-all

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  check-clang-format:
    runs-on: ubuntu-22.04
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: '0'
      - name: Install dependencies
        run: |
           sudo apt update &&                             \
           sudo apt install --yes --no-install-recommends \
           clang-format-14                                \
           git
      - name: Check formatting
        run: ./contrib/scripts/check-clang-format.sh
        shell: bash
      - name: 'Upload clang-format diff'
        uses: actions/upload-artifact@v3
        if: success() || failure()
        with:
          name: clang_format_diff
          path: clang_format.diff
          retention-days: 1
      - run: echo "${{ github.event.number }}" > pr_number.txt
        if: success() || failure()
      - name: 'Upload PR number'
        uses: actions/upload-artifact@v3
        if: success() || failure()
        with:
          name: pr_number
          path: pr_number.txt
          retention-days: 1

  check-license-headers:
    runs-on: ubuntu-22.04
    timeout-minutes: 20
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: '0'
    - name: Check license headers
      run: ./contrib/scripts/check-license-headers.sh
      shell: bash
    - name: 'Upload missing license headers'
      uses: actions/upload-artifact@v3
      if: success() || failure()
      with:
        name: missing_license_headers
        path: missing_license_headers.txt
        retention-days: 1

  check-clang-tidy:
    runs-on: ubuntu-22.04
    timeout-minutes: 60
    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: |
         sudo apt update &&                             \
         sudo apt install --yes --no-install-recommends \
         build-essential                                \
         libboost-dev                                   \
         libcapstone-dev                                \
         libgrpc++-dev                                  \
         libssh2-1-dev                                  \
         vulkan-validationlayers-dev                    \
         libz-dev                                       \
         llvm-dev                                       \
         protobuf-compiler-grpc                         \
         pkg-config                                     \
         libvulkan-volk-dev                             \
         libvulkan-dev                                  \
         libopengl-dev                                  \
         libglx-dev                                     \
         mesa-common-dev                                \
         qtbase5-dev                                    \
         libgtest-dev                                   \
         libgmock-dev                                   \
         libprotobuf-dev
    - run: mkdir "build"
    - name: CMake Configure
      working-directory: ./build
      run: |
        cmake -DCMAKE_BUILD_TYPE=Debug                                                               \
         -DCMAKE_CXX_FLAGS="-march=sandybridge -fno-omit-frame-pointer -mno-omit-leaf-frame-pointer" \
         ${GITHUB_WORKSPACE}
    - uses: ZedThree/clang-tidy-review@79d70e7c89de1bda6ad68610cde18d2783749852 # 0.10.1
      with:
        build_dir: ./build
        config_file: '.clang-tidy'
        clang_tidy_version: '14'
        split_workflow: true
    - uses: actions/upload-artifact@v3
      with:
        name: clang_tidy_review
        path: |
          clang-tidy-review-output.json
          clang-tidy-review-metadata.json