# Copyright (c) 2022 The Orbit Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

name: release
on:
  schedule:
  - cron: '0 7 * * 1,3,5'
  # This is for testing the action only.
  pull_request:
    branches:
    - 'main'

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  build-debian-package:
    runs-on: ubuntu-22.04
    timeout-minutes: 180
    env:
      CCACHE_BASEDIR: "${GITHUB_WORKSPACE}"
      CCACHE_DIR: "${GITHUB_WORKSPACE}/.ccache"
      CCACHE_COMPRESS: "true"
      CCACHE_COMPRESSLEVEL: "6"
      CCACHE_MAXSIZE: "400M"
    steps:
      - run: ls .
      - uses: actions/checkout@v3
        with:
          fetch-depth: '0'
          path: orbit
      - run: cd orbit
      - run: ls .
      - name: Install dependencies
        run: |
           sudo apt update &&                             \
           sudo apt install --yes --no-install-recommends \
           build-essential                                \
           devscripts                                     \
           cmake                                          \
           ccache                                         \
           git                                            \
           equivs                                         \
           fakeroot
      - name: Install Debian Build Dependencies
        run: ls . && sudo mk-build-deps --install debian/control
      - run: mkdir build && cd build
      - name: Save CCache Timestamp
        id: ccache_timestamp
        run: echo "timestamp=$(date +%m-%d-%Y--%H:%M:%S)" >> $GITHUB_OUTPUT
      - name: Setup CCache Files
        uses: actions/cache@v3
        with:
          path: .ccache
          key: debian-ccache-${{ steps.ccache_timestamp.outputs.timestamp }}
          restore-keys: |
            debian-ccache-
            ccache-
      - run: ccache -p
      - run: ccache -z
      - name: Build Debian Package
        run: debuild --set-envvar=CMAKE_C_COMPILER_LAUNCHER=ccache \
             --set-envvar=CMAKE_CXX_COMPILER_LAUNCHER=ccache       \
             --preserve-envvar=CCACHE_BASEDIR                      \
             --preserve-envvar=CCACHE_DIR                          \
             --preserve-envvar=CCACHE_COMPRESS                     \
             --preserve-envvar=CCACHE_COMPRESSLEVEL                \
             --preserve-envvar=CCACHE_MAXSIZE                      \
             -b
      - name: CCache Stats
        run: ccache -s
      - name: Archive Debian Packages
        uses: actions/upload-artifact@v3
        with:
          name: debian-packages
          path: ..
